set(NABLA_VERSION_MAJOR 0)
set(NABLA_VERSION_MINOR 1)
set(NABLA_VERSION_PATCH 0)

set(NABLA_VERSION_INFO "${NABLA_VERSION_MAJOR}.${NABLA_VERSION_MINOR}.${NABLA_VERSION_PATCH}")

message("Version: ${NABLA_VERSION_INFO}")