#ifndef NABLA_VSYS_SETTINGS_HPP
#define NABLA_VSYS_SETTINGS_HPP

namespace NABLA 
{
namespace VSYS
{
    constexpr int NABLA_VSYS_SETTINGS_LOCAL_MEMORY_BYTES  = 125000;
    constexpr int NABLA_VSYS_SETTINGS_GLOBAL_MEMORY_BYTES = 62500000;
    constexpr int NABLA_VSYS_SETTINGS_MAX_FUNCTIONS       = 100000;

}
}

#endif