#ifndef DEL_PRE_PROCESSOR_HPP
#define DEL_PRE_PROCESSOR_HPP

#include "Errors.hpp"
#include <string>
#include <vector>
#include <filesystem>
#include <stack>

namespace DEL
{
    //! \brief A preprocessor!
    class Preprocessor
    {
    public:
        //! \brief Construct the preprocessor
        //! \param error_man The error manager
        Preprocessor(Errors & error_man);

        //! \brief Destruct the preprocessor
        ~Preprocessor();

        //! \brief Process a file
        //! \param filename The entry file
        void process(const char * const filename);

        //! \brief Get the name of the filename generated by the preprocessor
        //! \returns Filename of preprocessed file
        std::string get_preprocessed_filename() const;

        //! \brief Add a path to look for to resolve use / include statements
        //! \param path The path to include
        void add_include_path(std::string path);

        //! \brief Get a line given the line number of the preprocessed file
        //! \param line_number The line number
        //! \returns The line at the given index
        std::string fetch_line(int line_number);

        //! \brief Get the line number of the user's input file given the preprocessed file's line number
        //! \param line_number The line number of the pre-processed file
        //! \returns Translated line number 
        uint64_t    fetch_user_line_number(int line_number);

    private:

        void process_file(std::string file);
        void process_line(std::string line, uint64_t number);

        struct line_no_pair
        {
            std::string line;
            uint64_t    number;
        };

        std::vector<line_no_pair> pre_processed_pair;   // Resulting preprocessed file with original line indexing
        std::vector<std::string> include_paths;         // Paths to search for use statements

        std::stack<std::string> current_file_stack;     // File processing stack for generating @file directives
        std::vector<std::string> included_files;        // Files already included

        Errors & error_man;
        bool preproc_ready;
        std::string default_path;
        std::string preprocessed_file;
    };
}

#endif 