#ifndef DEL_ASM_INIT_SUPPORT_HPP
#define DEL_ASM_INIT_SUPPORT_HPP


/*

    Note : This information should not be directly used by anyone except for the AsmSupport class

*/

namespace DEL
{
namespace BUILT_IN
{
    
static const std::string ASM_FILE_START = R"asmstart(

;
;   This file was auto generated by the DEL compiler 
;   At the time of this generation DEL compiler was heavily under development
;   by someone who knows very little about compiler design
;       - Josh A. Bosley

.file "DEL_Lang"

.init __del__program__init

)asmstart";

static const std::string ASM_INIT_FUNCTION = R"init(

<__del__program__init:

    call main           ; Entry to the user's application

    ; Clear out the external memory device

    lsh r0 $13 $56      ; Move DS id into position
    lsh r1 $50 $48      ; Move sub-id for 'reset' into position
    or r10 r0 r1        ; Or together to create command into r10

    ; Shutdown network device 

    lsh r0 $11 $56      ; Network device
    lsh r1 $50 $48      ; Move sub-id for 'shutdown' into position
    or r10 r0 r1        ; Or together to create command into r10

    exit
>

)init";


}
}


#endif 