#ifndef DEL_ASM_INIT_SUPPORT_HPP
#define DEL_ASM_INIT_SUPPORT_HPP


/*

    Note : This information should not be directly used by anyone except for the AsmSupport class

*/

namespace DEL
{
namespace BUILT_IN
{
    
static const std::string ASM_FILE_START = R"asmstart(

;
;   This file was auto generated by the DEL compiler 
;   At the time of this generation DEL compiler was heavily under development
;   by someone who knows very little about compiler design
;       - Josh A. Bosley

.file "DEL_Lang"

.init __del__program__init

)asmstart";

static const std::string ASM_INIT_FUNCTION = R"init(

<__del__program__init:

    call main       ; Entry to the user's application

    exit
>

)init";


}
}


#endif 