#ifndef NABLA_VM_RETURN_CODES_H
#define NABLA_VM_RETURN_CODES_H

#define VM_ERROR_NULL_VM   -1
#define VM_ERROR_FILE_OPEN -10
#define VM_ERROR_FAILED_TO_LOAD_CONSTANTS -11


#define VM_ERROR_FAILED_TO_ALLOCATE -20
#endif